# Permalinks
permalink:           pretty

# Setup
title:               Ake Paramadilok
tagline:             TBA
url:                 http://akedilok.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ake Paramadilok
  url:               
  email:             ake253@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/akedilok

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
